//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTI.DataBase.Objects.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RTI.DataBase.Objects.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to column_name,mapping
        ///agency_cd,
        ///site_no,
        ///station_nm,
        ///site_tp_cd,
        ///lat_va,
        ///long_va,
        ///dec_lat_va,
        ///dec_long_va,
        ///coord_meth_cd,
        ///coord_acy_cd,
        ///coord_datum_cd,
        ///dec_coord_datum_cd,
        ///district_cd,
        ///state_cd,
        ///county_cd,
        ///country_cd,
        ///land_net_ds,
        ///map_nm,
        ///map_scale_fc,
        ///alt_va,
        ///alt_meth_cd,
        ///alt_acy_va,
        ///alt_datum_cd,
        ///huc_cd,
        ///basin_cd,
        ///topo_cd,
        ///data_types_cd,
        ///instruments_cd,
        ///construction_dt,
        ///inventory_dt,
        ///drain_area_va,
        ///contrib_drain_area_va,
        ///tz_cd,
        ///local_time_fg,
        ///reliability_cd,
        ///gw_file_cd,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ColumnMappingXref {
            get {
                return ResourceManager.GetString("ColumnMappingXref", resourceCulture);
            }
        }
    }
}
